### ISSUE TITLE
ADMIN drop-down

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#18]
"Create or Edit Business Card" should also be an option in Dashboard

**Comment by wgimson** [comment]
@macy125 @alexgimson86 
pulling this one....

**Comment by wgimson** [comment]
@macy125 @alexgimson86 
I'm also going to fix the dashboard buttons so they're all the same width on this one...

![image](https://user-images.githubusercontent.com/676537/136109957-46a669c8-15a6-4d68-9474-33eb2b7950a2.png)

**Comment by wgimson** [comment]
![image](https://user-images.githubusercontent.com/676537/136112162-4f07b20d-c97c-4aeb-8ef7-4d20aea76763.png)
