### ISSUE TITLE
Profile Information

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#21]
https://serene-everglades-65051.herokuapp.com/account

What fields (other than subscription info) do we need here?

**Comment by wgimson** [comment]
@macy125 
Minimally we need a Business Name and Email. Might be a good idea to go over the fields in the Business Card Form and see if we want the admin to be able to edit any of those *for the account*. We just need to think about what information we want to collect from the admin about the account in general. 

https://serene-everglades-65051.herokuapp.com/dashboard/business-card/create-business-card-form

**Comment by wgimson** [comment]
@macy125 
Looking over this I think we should get rid of gender but keep the remaining. They could be useful and it's all volutary. they don't have to fill any of this extra info out if they don't want to, but if they do that's more data to store. 

Also might want to think about additional fields. I guess anything at the admin level that is not already included in the Business Card info.

**Comment by macy125** [comment]
i don't see gender. 

(how do i assign this to myself?)
