### ISSUE TITLE
Download QR Code 

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#41]
https://serene-everglades-65051.herokuapp.com/dashboard/generateQRCode

This is more of a question -
How can they download the QR code? 
Are the options when you right-click relevant? DO WE WANT THEM TO GENERATE A QR CODE FOR A QR CODE?! wtf

**Comment by wgimson** [comment]
@macy125 @alexgimson86 

QR Codes now download as a PNG image to the browser
