### ISSUE TITLE
#1 Dashboard

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#51]
https://serene-everglades-65051.herokuapp.com/dashboard/dashboard

Attached is how QRd should look. Can we get the links and QRd in place (it's okay if the links don't work)?

![QRd proto](https://user-images.githubusercontent.com/90807434/156906781-ca5bd24e-11e3-4f82-b0d1-e9cd6d391905.PNG)
-

**Comment by wgimson** [comment]
@macy125 ok, do you want separate tasks for each link and where it goes to?

**Comment by wgimson** [comment]
@macy125 
CLOSED - but we must discuss where the links go.
