### ISSUE TITLE
registration link on home page

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#54]
create a "register/sign up" link on homepage:

https://serene-everglades-65051.herokuapp.com/

Use this from "ADMIN DASHBOARD" document on slack:
COMPANY INFO
COMPANY NAME
COMPANY ADDRESS
COMPANY PHONE
COMPANY WEBSITE
CLASS OF TRADE
NUMBER OF SHOWROOMS
OWNER/CEO
REGISTERED AS
EIN
METHOD OF PAYMENT

**Comment by wgimson** [comment]
@wgimson @macy125 
This will replace the current _**CREATE ACCOUNT**_ workflow

**Comment by wgimson** [comment]
These must go to PENDING accounts first, then get approved

**Comment by wgimson** [comment]
@macy125  

Deployed, user can now register for an account, then the admin can approve their registration. When that happens, a new user is created, with all the new fields provided above.  

https://serene-everglades-65051.herokuapp.com/admin/registeredUsers
