### ISSUE TITLE
Submitting Registration leads to blank page - need conf

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#61]
Need some kind of confirmation page once application is submitted. For now it can say:

Thank you for registering! 

Please check your e-mail for updates.

**Comment by wgimson** [comment]
redirect to thank you page w info

**Comment by wgimson** [comment]
@macy125 
![image](https://user-images.githubusercontent.com/676537/180628978-5062124f-57d2-492b-9ca6-74ed4ca3042e.png)
