### ISSUE TITLE
OUR DASHBOARD 

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#64]
https://serene-everglades-65051.herokuapp.com/dashboard/dashboard

Our dashboard shouldn't include anything except for managing registrations. QRd and all those buttons should be removed. 

Would it be possible to have an "approved accounts" directory as well?  

one link for registrations, separate link for current accounts...

**Comment by wgimson** [comment]
Let's create a new menu item drop down called 'Admin Dashboard'. Will only exist for the single admin account. 

the admins dashboard will have a link that reads 'All Accounts', 'Declined Accounts', 'Approved Accounts' -0 one filterable table

- and one for 'Registrations'
