### ISSUE TITLE
Registration Page Info

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#65]
What info should the application page/registration include? Any pre-reqs? 

https://serene-everglades-65051.herokuapp.com/signup

**Comment by macy125** [comment]
![REF FORM SCREEN SHOT](https://user-images.githubusercontent.com/90807434/169721536-1c90f8da-6cb5-4f22-8502-70245059a9e5.PNG)

**Comment by macy125** [comment]
registration form

**Comment by wgimson** [comment]
@macy125 
Check the deployed app on this I believe it's complete...
