### ISSUE TITLE
Request Follow Up Button

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#71]
Create form for request a follow up button

**Comment by macy125** [comment]
see form attached.

Also needs to include a submit button and a banner with the following confirmation:

Thank you for your submission! We will be in touch with you soon.

**Comment by macy125** [comment]
![FOLLOW UP FORM](https://user-images.githubusercontent.com/90807434/172028485-22baedb9-c137-4d75-827c-0e24cf9e71e1.PNG)

**Comment by wgimson** [comment]
(macy)

create table like registered users waiting: http://localhost:5000/admin/registeredUsers

EX. of scenario
end-user comes upon showroom, no time to visit or take info. 
scans QR to select "follow-up" link for admin/vendor to send them more info for later
end-user completes form for admin and receives confirmation in form of pop-up
admin receives end-user's form in dashboard (in form of table - exportable to excel)

**Comment by wgimson** [comment]
admin receives alert on nav bar similar to new e-mail alert on outlook (just icon, no numbers)
admin selects link to view table and table is sorted by newest to oldest request
table shows all information in form above 
admin can select row to acknowledge (we'll discuss how this looks later, just make the table first)

**Comment by wgimson** [comment]
@macy125 NOTE - we have to discuss the ALERT for new follow up request
