### ISSUE TITLE
Figure out which Registration Fields you want Displayed in Registration Table

### ISSUE THREAD

**Issue by wgimson** [wgimson/QRdly#75]
pick the subset of fields you want displayed in the table row from the registration link at bottom. Remember, there will be an edit button for each row that navigates to a form with ALL the data to edit, so only the most important fields need be displayed in the table itself. 

https://serene-everglades-65051.herokuapp.com/signup

**Comment by macy125** [comment]
![preview in admin dashboard](https://user-images.githubusercontent.com/90807434/169722092-a52fe3d5-a677-4dff-8351-49a4989a16a1.PNG)
