### ISSUE TITLE
REgistration Waiting List/Table

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#78]
Update fields to pic attached

![preview in admin dashboard](https://user-images.githubusercontent.com/90807434/169722883-e6475276-7c77-4a0d-8c26-c9c558e7f1b4.PNG)

**Comment by macy125** [comment]
this means the rows for the registered users table

**Comment by wgimson** [comment]
@macy125 
![image](https://user-images.githubusercontent.com/676537/180629505-142ea98d-5cf9-4432-bca0-1dfceadff06f.png)
