### ISSUE TITLE
Button edits

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#80]
remove buttons with red x
![qrdedits](https://user-images.githubusercontent.com/90807434/170169562-8272591f-2a47-4f2d-ab9b-a80f8471b6b0.jpg)

**Comment by wgimson** [comment]
@macy125 

![image](https://user-images.githubusercontent.com/676537/172276860-8f40cc99-af1d-4aa7-b258-c18ab6de4beb.png)
