### ISSUE TITLE
New Cal

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#82]
See attached for new calendar workflow

[CAL WIREFRAME.pdf](https://github.com/wgimson/QRdly/files/8857240/CAL.WIREFRAME.pdf)
w

**Comment by wgimson** [comment]
@macy125 cleaned up the calendar code a whoooooooole lot....now I can work on the calendars and change things around without breaking everything much more easily.

**Comment by wgimson** [comment]
![image](https://user-images.githubusercontent.com/676537/178410340-8cd92853-48ae-4817-966e-b5865c007f95.png)

This is probably *possible* with FullCalendar CustomButtons, but it would be a lot of work. I suggest for first release we implement a simple previous and next button and save the actual days/dates for a the next version.

**Comment by wgimson** [comment]
@macy125 Note

**Comment by wgimson** [comment]
@macy125 
DONE!
